{{- if .Values.akash_node.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: akash-node
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 1317
      name: akashd-api
    - port: 9090
      name: akashd-grpc
    - port: 26656
      name: akashd-p2p
    - port: 26657
      name: akashd-rpc
  selector:
    app: akash-node
{{- end }}
